title: Olly Overend's Notes
url: "https://OliverOverend.github.io"
description: ""

github_username: OliverOverend
linkedin_username: ollyoverend

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

minima:
  skin: auto

show_excerpts: True

disqus:
  shortname: oliveroverend-github-io

header_pages: 
  - index.md
  - posts.html
