title: Oliver Overend
url: "https://OliverOverend.github.io"
description: ""

github_username: OliverOverend
linkedin_username: ollyoverend

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

minima:
  skin: dark

show_excerpts: False

disqus:
  shortname: oliveroverend-github-io
